services:
  api:
    build: .
    ports:
      - "80:8000"
    environment:
      TZ: Europe/Warsaw
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=5
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./logs:/app/logs
    depends_on:
      - postgres
      - pgadmin
    networks:
      - autoria_network
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: autoria_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "32:5432"
    networks:
      - autoria_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.4-bookworm
    container_name: redis
    ports:
      - "79:6379"
    networks:
      - autoria_network
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  scrapy_app:
    build: .
    container_name: autoria_scrapy
    # üëá –í–ê–ñ–õ–ò–í–û: –ø—ñ–¥–∫–ª—é—á–∞—î–º–æ —Ñ–∞–π–ª–∏ –∑ —Ö–æ—Å—Ç–∞ –≤—Å–µ—Ä–µ–¥–∏–Ω—É
    volumes:
      - ./:/app
    ports:
      - "2222:22"  # üëà SSH –¥–æ—Å—Ç—É–ø –¥–ª—è PyCharm (localhost:2222)
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      POSTGRES_HOST: postgres
      DOCKER_ENV: true
      TZ: Europe/Warsaw
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - autoria_network
    restart: unless-stopped
    # TTY –ø–æ—Ç—Ä—ñ–±–µ–Ω –¥–ª—è –∫–æ—Ä–µ–∫—Ç–Ω–æ—ó —Ä–æ–±–æ—Ç–∏ –¥–µ—è–∫–∏—Ö –ø—Ä–æ—Ü–µ—Å—ñ–≤
    tty: true
  pgadmin:
    image: dpage/pgadmin4
    container_name: autoria_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - autoria_network

volumes:
  postgres_data:
  redis_data:
networks:
  autoria_network:
    driver: bridge